- name: Install some requirements
  yum:
    name:
      - python-psycopg2
      - epel-release
      - expect
      - unzip

- name: Copy ICAT db creation script
  template:
    src: icat.sql
    dest: "/tmp"

- name: Create ICAT db and user
  shell: sudo -u postgres psql < icat.sql
  args:
    chdir: /tmp

- name: Import iRODS repo public key
  command: rpm --import https://packages.irods.org/irods-signing-key.asc

- name: Add iRODS yum repo
  get_url:
    url: "https://packages.irods.org/renci-irods.yum.repo"
    dest: "/etc/yum.repos.d/renci-irods.yum.repo"

- name: Make sure the public key is downloaded
  command: "yum -y check-update"
  ignore_errors: yes

- name: Install iRODS packages
  yum:
    name:
      - irods-server
      - irods-database-plugin-postgres

- name: Copy setup response script to server
  template:
    src: setup.tcl
    dest: "/home/vagrant"
    mode: "u+x"

- name: Run setup
  command: "/home/vagrant/setup.tcl"

- name: Download example files
  get_url:
    url: "ftp://ftp.renci.org/pub/irods/training/training_jpgs.zip"
    dest: "/home/vagrant"